name: keep-render-awake
on:
  schedule:
    - cron: "*/10 * * * *" # every 10 min
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSf https://stream-it-api.onrender.com > /dev/null
