name: keep-render-awake

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # lets you run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl -sSf https://stream-it-api.onrender.com/ping > /dev/null
